language: c++
compiler: gcc

script:
  - make test
  - make web-test

after_success:
  - ./gcov.sh

install:
  - pip install --user codecov

before_install:
    - sudo apt-get install -qq libc6-dbg valgrind
